fileVersion: 1
id: "388"
mappingDefinitions:
  SOURCE:
    database: ANANDHIS_DEV
    schema: SOURCE_DATA
  TARGET:
    database: ANANDHIS_DEV
    schema: TARGET_DEV
name: New Environment
type: Environment
