fileVersion: 1
id: "388"
mappingDefinitions:
  SOURCE:
    database: ANANDHIS_DEV
    schema: SOURCE_DATA
  SOURCE2:
    database: POONAMM_DEV
    schema: EDW_QA
  TARGET:
    database: ANANDHIS_DEV
    schema: TARGET_ACC
name: New Environment
type: Environment
